# Splitfy
services:
  api:
    container_name: splitfy-backend
    image: splitfy-backend:latest
    build: ../puc-rio-backend
    ports:
        - "5000:5000"
    restart: always

  web:
    container_name: splitfy-frontend
    image: splitfy-frontend:latest
    build: ../puc-rio-frontend
    ports:
        - "3000:3000"
    restart: always
    environment:
      - REACT_APP_VERSION=v0.1.0
      - GENERATE_SOURCEMAP=false
    depends_on:
      - api
